// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsAaz-dMfAldT6JI0UMfPbjd-Tq4yeEQ',
    appId: '1:893826836090:android:d461892e7c7a414ed1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    databaseURL: 'https://testing-aa21c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-aa21c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfe2CPWVcygUVFFWUHHE_TIdsR13JVas',
    appId: '1:893826836090:ios:01c8ed084998d898d1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    databaseURL: 'https://testing-aa21c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-aa21c.appspot.com',
    androidClientId: '893826836090-0rrm1thltaaiqk9i476l6pm96mff7mjc.apps.googleusercontent.com',
    iosClientId: '893826836090-aq5u1q6ve34vit6h4erqtu46bum9gjb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceMarking',
  );

}